version: '3.3'

services:
  app:
    build:
      context: ./react/
      dockerfile: ./Dockerfile
    ports:
      - "127.0.0.1:3000:3000"

  backend:
    build:
      context: ./fastapi/
      dockerfile: ./Dockerfile
    ports:
      - "127.0.0.1:8000:8000"