name: CI/CD Workflow

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.9

      - name: Install Dependencies
        run: |
          pip install -r fastapi/requirements.txt

  deploy:
    runs-on: ubuntu-latest

    needs: build

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.9

      - name: Set up MLflow
        run: |
          pip install mlflow

#      - name: Deploy Model
#        run: |
#          mlflow login -u ${{ secrets.MLFLOW_USERNAME }} -p ${{ secrets.MLFLOW_PASSWORD }} -e ${{ secrets.MLFLOW_ENDPOINT }}
#          mlflow models serve -m models:/v1 -h 0.0.0.0 -p 8000

#      - name: Deploy Pickle File to MLflow Registry
#        run: |
#          mlflow login -u ${{ secrets.MLFLOW_USERNAME }} -p ${{ secrets.MLFLOW_PASSWORD }} -e ${{ secrets.MLFLOW_ENDPOINT }}
#          mlflow registry --url ${{ secrets.MLFLOW_REGISTRY_URL }}
#          mlflow registry add-model -m models:/v1 -n random_forest_model --artifact-path random_forest_model.pkl

      - name: Deploy FastAPI App
        run: |
          docker build -t fastapi_ia .
          docker tag fastapi_ia:latest fastapi_ia:v1

      - name: Push Docker Image
        run: |
          echo ${{ secrets.DOCKER_PASSWORD }} | docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin
          docker push fastapi_ia:v1