name: CI/CD Workflow

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.9

      - name: Install Dependencies
        run: |
          pip install -r fastapi/requirements.txt
          pip install dvc

      - name: Initialize DVC and Set Up DagsHub Remote
        run: |
          dvc init
          dvc remote add origin dvc+https://dagshub.com/lucasdsm78/fraud-detection-ia-repo.dvc

      - name: Add Model and Data to DVC
        run: |
          dvc add fastapi/random_forest_model.pkl
          dvc push -r origin

  deploy:
    runs-on: ubuntu-latest

    needs: build

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.9

      - name: Deploy FastAPI App
        run: |
          cd fastapi
          docker build -t lucasdsm78/fastapi_ia:v1 .
          docker tag lucasdsm78/fastapi_ia:v1 lucasdsm78/fastapi_ia:latest

      - name: Push Docker Image
        run: |
          cd fastapi
          echo ${{ secrets.DOCKER_PASSWORD }} | docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin
          docker push lucasdsm78/fastapi_ia:v1